# Generated by Django 4.0.6 on 2022-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('mobile', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=500)),
                ('business_scale', models.CharField(max_length=500)),
                ('user_type', models.CharField(max_length=500)),
                ('no_of_users', models.CharField(max_length=500)),
                ('deployment', models.CharField(max_length=500)),
                ('os', models.CharField(max_length=500)),
                ('mobile_app', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegInhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('mobile', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=500)),
                ('business_scale', models.CharField(max_length=500)),
                ('user_type', models.CharField(max_length=500)),
                ('no_of_users', models.CharField(max_length=500)),
                ('deployment', models.CharField(max_length=500)),
                ('os', models.CharField(max_length=500)),
                ('mobile_app', models.CharField(max_length=500)),
            ],
        ),
    ]
