# Generated by Django 4.0.6 on 2022-08-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientregfreelance_clientreginhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
