# Generated by Django 4.0.6 on 2022-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientregfreelance_approve_clientreginhouse_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='emp_mail',
            field=models.EmailField(max_length=500, null=True),
        ),
    ]
