# Generated by Django 4.0.7 on 2022-08-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientregfreelance_emp_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientregfreelance',
            name='emp_mail',
        ),
    ]
