# Generated by Django 4.0.7 on 2022-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_clientregfreelance_emp_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='to_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='to_emp',
            field=models.BooleanField(default=False),
        ),
    ]
