# Generated by Django 4.0.7 on 2022-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_clientregfreelance_to_emp_clientreginhouse_to_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreginhouse',
            name='to_emp',
        ),
        migrations.AddField(
            model_name='clientregfreelance',
            name='accept_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='accept_project',
            field=models.BooleanField(default=False),
        ),
    ]
