# Generated by Django 4.0.7 on 2022-08-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_clientreginhouse_to_emp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientregfreelance',
            old_name='to_emp',
            new_name='to_employee',
        ),
    ]
