# Generated by Django 4.0.5 on 2022-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_rename_to_emp_clientregfreelance_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='finish_project',
            field=models.BooleanField(default=False),
        ),
    ]
