# Generated by Django 4.0.5 on 2022-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientregfreelance_finish_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreginhouse',
            name='finish_project',
            field=models.BooleanField(default=False),
        ),
    ]
