# Generated by Django 4.0.5 on 2022-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_clientreginhouse_finish_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='client_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='client_approve',
            field=models.BooleanField(default=False),
        ),
    ]
