# Generated by Django 4.0.7 on 2022-08-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_clientregfreelance_client_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='pricing',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='pricing',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
