# Generated by Django 4.0.7 on 2022-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_clientregfreelance_pricing_clientreginhouse_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregfreelance',
            name='send_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientreginhouse',
            name='send_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
