# Generated by Django 4.0.6 on 2022-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('phone', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
