# Generated by Django 4.0.6 on 2022-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('emp_id', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('age', models.IntegerField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('job_title', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
