# Generated by Django 4.0.6 on 2022-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_employee', '0002_freelanceemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceemployee',
            name='age',
            field=models.IntegerField(),
        ),
    ]
