# Generated by Django 4.0.6 on 2022-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_employee', '0003_alter_freelanceemployee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceemployee',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
