# Generated by Django 4.0.7 on 2022-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_employee', '0004_freelanceemployee_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceemployee',
            name='client_approve',
            field=models.BooleanField(default=False),
        ),
    ]
