# Generated by Django 4.0.7 on 2022-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_employee', '0005_freelanceemployee_client_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceemployee',
            name='from_client',
            field=models.BooleanField(default=False),
        ),
    ]
