# Generated by Django 4.0.6 on 2022-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('emp_id', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=500)),
                ('job_title', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
