# Generated by Django 4.0.7 on 2022-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_inhouseemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhouseemployee',
            name='client_approve',
            field=models.BooleanField(default=False),
        ),
    ]
